kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node:19.4.0
    commands:
      - npm install

  - name: build_with_linux
    image: node:19.4.0
    commands:
      - apt-get update && apt-get upgrade -y
      - apt-get install -y libarchive-tools rpm
      - npm run build
