export const globalEvents = {
  play: "play",
  pause: "pause",
  playPause: "playPause",
  next: "next",
  previous: "previous",
  updateInfo: "update-info",
  hideSettings: "hideSettings",
  refreshMenuBar: "refreshMenubar",
  showSettings: "showSettings",
  storeChanged: "storeChanged",
  error: "error",
  getUniversalLink: "getUniversalLink",
  log: "log",
  toggleFavorite: "toggleFavorite",
  toggleShuffle: "toggleShuffle",
  toggleRepeat: "toggleRepeat",
};
