export const UI_SELECTORS = {
  player: '*[id="video-one"]',
  play: '*[data-test="play"]',
  pause: '*[data-test="pause"]',
  next: '*[data-test="next"]',
  previous: 'button[data-test="previous"]',
  title: '*[data-test^="footer-track-title"]',
  artists: '*[data-test^="grid-item-detail-text-title-artist"]',
  home: '*[data-test="menu--home"]',
  back: '[aria-label="Back"]',
  forward: '[aria-label="Next"]:not([data-test="next"])',
  search: '[class^="searchField"]',
  shuffle: '*[data-test="shuffle"]',
  repeat: '*[data-test="repeat"]',
  account: '*[data-test^="profile-image-button"]',
  media: '*[data-test="current-media-imagery"]',
  image: "img",
  bar: '*[data-test="progress-bar"]',
  footer: "#footerPlayer",
  mediaItem: "[data-type='mediaItem']",
  album_header_title: '*[class^="_playingFrom"] span:nth-child(2)',
  playing_from: '*[class^="_playingFrom"] span:nth-child(2)',
  queue_album: "*[class^=playQueueItemsContainer] *[class^=groupTitle] span:nth-child(2)",
  currentlyPlaying: "[class^='isPlayingIcon'], [data-test-is-playing='true']",
  album_name_cell: '[class^="album"]',
  tracklist_row: '[data-test="tracklist-row"]',
  volume: '*[data-test="volume"]',
  favorite: '*[data-test="footer-favorite-button"]',
};
